# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
    output_format = "i3bar"
    markup = "pango"
    interval = 1
    colors = true
    color_good = "#c3e88d"
    color_degraded = "#ffc777"
    color_bad = "#ff007c"
}


order += "disk /"
order += "cpu_usage"
order += "memory"
order += "ethernet _first_"
order += "tztime local"


tztime local {
        format = "  %d.%m.%Y %H:%M:%S "
}

disk "/" {
      format = "<span foreground='#ff007c'>  </span> %avail / %total"
      low_threshold = 10
      format_below_threshold = "  %avail / %total"
      threshold_type = "percentage_free"
      color_good = "#c3e88d"
}

cpu_usage {
    format = "<span foreground='#c53b53'>  </span> %usage "
    format_above_threshold = "  %usage"
    format_above_degraded_threshold = "  %usage"
    max_threshold = 90
    degraded_threshold = 75
}

ethernet _first_ {
  format_up = "<span foreground='#41a6b5'> 󰈀 </span> %ip (%speed)"
  format_down = " 󰈀: down"
}

memory {
    format = "<span foreground='#ff757f'> 󰍛</span>  %used / %total"
    threshold_degraded = 20%
    threshold_critical = 10%
}
